package com.example.demo.entity;
// Generated 8 Nov, 2021 4:19:09 PM by Hibernate Tools 5.4.11.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Car generated by hbm2java
 */
@Entity
@Table(name="CAR"
    ,schema="PUBLIC"
    ,catalog="TESTDB"
)
public class Car  implements java.io.Serializable {


     private Integer pkCarId;
     private String brand;
     private String model;
     private Set<Engineer> engineers = new HashSet<Engineer>(0);

    public Car() {
    }

    public Car(String brand, String model, Set<Engineer> engineers) {
       this.brand = brand;
       this.model = model;
       this.engineers = engineers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_CAR_ID", unique=true, nullable=false)
    public Integer getPkCarId() {
        return this.pkCarId;
    }
    
    public void setPkCarId(Integer pkCarId) {
        this.pkCarId = pkCarId;
    }

    
    @Column(name="BRAND", length=100)
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }

    
    @Column(name="MODEL", length=100)
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="car")
    public Set<Engineer> getEngineers() {
        return this.engineers;
    }
    
    public void setEngineers(Set<Engineer> engineers) {
        this.engineers = engineers;
    }




}


