package com.example.demo.entity;
// Generated 8 Nov, 2021 4:19:09 PM by Hibernate Tools 5.4.11.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name="COUNTRY"
    ,schema="PUBLIC"
    ,catalog="TESTDB"
)
public class Country  implements java.io.Serializable {


     private Integer pkCountryId;
     private String name;
     private String officiallang;
     private Integer size;
     private Set<Unrepresentative> unrepresentatives = new HashSet<Unrepresentative>(0);

    public Country() {
    }

    public Country(String name, String officiallang, Integer size, Set<Unrepresentative> unrepresentatives) {
       this.name = name;
       this.officiallang = officiallang;
       this.size = size;
       this.unrepresentatives = unrepresentatives;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_COUNTRY_ID", unique=true, nullable=false)
    public Integer getPkCountryId() {
        return this.pkCountryId;
    }
    
    public void setPkCountryId(Integer pkCountryId) {
        this.pkCountryId = pkCountryId;
    }

    
    @Column(name="NAME", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="OFFICIALLANG", length=100)
    public String getOfficiallang() {
        return this.officiallang;
    }
    
    public void setOfficiallang(String officiallang) {
        this.officiallang = officiallang;
    }

    
    @Column(name="SIZE")
    public Integer getSize() {
        return this.size;
    }
    
    public void setSize(Integer size) {
        this.size = size;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<Unrepresentative> getUnrepresentatives() {
        return this.unrepresentatives;
    }
    
    public void setUnrepresentatives(Set<Unrepresentative> unrepresentatives) {
        this.unrepresentatives = unrepresentatives;
    }




}


