package com.example.demo.entity;
// Generated 8 Nov, 2021 4:19:09 PM by Hibernate Tools 5.4.11.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="STUDENT"
    ,schema="PUBLIC"
    ,catalog="TESTDB"
)
public class Student  implements java.io.Serializable {


     private Integer studentid;
     private String name;
     private Set<StudentClass> studentClasses = new HashSet<StudentClass>(0);

    public Student() {
    }

    public Student(String name, Set<StudentClass> studentClasses) {
       this.name = name;
       this.studentClasses = studentClasses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="STUDENTID", unique=true, nullable=false)
    public Integer getStudentid() {
        return this.studentid;
    }
    
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }

    
    @Column(name="NAME", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="students")
    public Set<StudentClass> getStudentClasses() {
        return this.studentClasses;
    }
    
    public void setStudentClasses(Set<StudentClass> studentClasses) {
        this.studentClasses = studentClasses;
    }




}


