package com.example.demo.entity;
// Generated 8 Nov, 2021 4:19:09 PM by Hibernate Tools 5.4.11.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * StudentClass generated by hbm2java
 */
@Entity
@Table(name="STUDENT_CLASS"
    ,schema="PUBLIC"
    ,catalog="TESTDB"
)
public class StudentClass  implements java.io.Serializable {


     private Integer classid;
     private String course;
     private Set<Student> students = new HashSet<Student>(0);

    public StudentClass() {
    }

    public StudentClass(String course, Set<Student> students) {
       this.course = course;
       this.students = students;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CLASSID", unique=true, nullable=false)
    public Integer getClassid() {
        return this.classid;
    }
    
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    
    @Column(name="COURSE", length=100)
    public String getCourse() {
        return this.course;
    }
    
    public void setCourse(String course) {
        this.course = course;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="STUDENTCLASSRELATION", schema="PUBLIC", catalog="TESTDB", joinColumns = { 
        @JoinColumn(name="CLASSID", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="STUDENTID", nullable=false, updatable=false) })
    public Set<Student> getStudents() {
        return this.students;
    }
    
    public void setStudents(Set<Student> students) {
        this.students = students;
    }




}


