package com.example.demo.entity;
// Generated 7 Nov, 2021 1:04:35 PM by Hibernate Tools 5.4.11.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StudentclassrelationId generated by hbm2java
 */
@Embeddable
public class StudentclassrelationId  implements java.io.Serializable {


     private int studentid;
     private int classid;

    public StudentclassrelationId() {
    }

    public StudentclassrelationId(int studentid, int classid) {
       this.studentid = studentid;
       this.classid = classid;
    }
   


    @Column(name="STUDENTID", nullable=false)
    public int getStudentid() {
        return this.studentid;
    }
    
    public void setStudentid(int studentid) {
        this.studentid = studentid;
    }


    @Column(name="CLASSID", nullable=false)
    public int getClassid() {
        return this.classid;
    }
    
    public void setClassid(int classid) {
        this.classid = classid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentclassrelationId) ) return false;
		 StudentclassrelationId castOther = ( StudentclassrelationId ) other; 
         
		 return (this.getStudentid()==castOther.getStudentid())
 && (this.getClassid()==castOther.getClassid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStudentid();
         result = 37 * result + this.getClassid();
         return result;
   }   


}


